---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-sub-wshi
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-ch-wshi
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: app-helloworld
  name: app-helloworld
  namespace: ns-sub-wshi
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: app-helloworld
status: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: app-helloworld-placement-1
  namespace: ns-sub-wshi
spec:
  clusterSelector:
    matchLabels:
      local-cluster: "true"
---
apiVersion: v1
data:
  user: d3NoaQ==
  password: cmVkaGF0
kind: Secret
metadata:
  name: sec-chartmuseum
  namespace:  ns-ch-wshi
type: Opaque
---
apiVersion: v1
data:
  user: d3NoaQ==
  password: cmVkaGF0
kind: Secret
metadata:
  name: sec-chartmuseum
  namespace:  ns-sub-wshi
type: Opaque
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: app-helloworld-ch
  namespace: ns-ch-wshi
  labels:
    app: app-helloworld
spec:
  type: HelmRepo
  secretRef:
    name: sec-chartmuseum
    namespace: ns-ch-wshi
  pathname: 'http://chartmuseum-chartmuseum-ns-chartmuseum.apps.wshi-ocp-cluster-0.qe.lab.redhat.com/charts'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: app-helloworld-subscription-1
  namespace: ns-sub-wshi
  labels:
    app: app-helloworld
spec:
  channel: ns-ch-wshi/app-helloworld-ch
  name: helloworld
  packageFilter:
    version: "0.1.0"
  placement:
    placementRef:
      kind: PlacementRule
      name: app-helloworld-placement-1
