apiVersion: v1
kind: Namespace
metadata:
  name: ns-chartmuseum
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-chartmuseum
  namespace: ns-chartmuseum
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - app-chartmuseum
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-ch-chartmuseum
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: hchartmuseumgithubio-charts
  namespace: ns-ch-chartmuseum
spec:
  type: HelmRepo
  pathname: 'https://chartmuseum.github.io/charts'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: app-chartmuseum
  name: app-chartmuseum-subscription-1
  namespace: ns-chartmuseum
spec:
  channel: ns-ch-chartmuseum/hchartmuseumgithubio-charts
  name: chartmuseum
  packageOverrides:
  - packageName: chartmuseum
    packageAlias: chartmuseum
    packageOverrides:
    - path: spec
      value:
        securityContext:
          enabled: false
        env:
          open:
            DISABLE_API: false
            CONTEXT_PATH: charts
          secret:
            BASIC_AUTH_USER: wshi
            BASIC_AUTH_PASS: redhat
  placement:
    placementRef:
      kind: PlacementRule
      name: app-chartmuseum-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: app-chartmuseum
  name: app-chartmuseum-placement-1
  namespace: ns-chartmuseum
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'

